-- Extend Subject enum with common NSW HSC subjects.
ALTER TYPE "Subject" ADD VALUE 'MATHEMATICS';
ALTER TYPE "Subject" ADD VALUE 'CHEMISTRY';
ALTER TYPE "Subject" ADD VALUE 'PHYSICS';
ALTER TYPE "Subject" ADD VALUE 'BIOLOGY';
ALTER TYPE "Subject" ADD VALUE 'ECONOMICS';
ALTER TYPE "Subject" ADD VALUE 'BUSINESS_STUDIES';
ALTER TYPE "Subject" ADD VALUE 'LEGAL_STUDIES';
ALTER TYPE "Subject" ADD VALUE 'MODERN_HISTORY';
ALTER TYPE "Subject" ADD VALUE 'ANCIENT_HISTORY';
ALTER TYPE "Subject" ADD VALUE 'GEOGRAPHY';

